on: pull_request
name: Audit npm packages on pull request
jobs:
  npmAudit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm audit
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
